### ISSUE TITLE
Add possibility to resize the list

### ISSUE THREAD

**Issue by paulcodiny** [BorisTheB1ad3/listy#2]
The width should be stuck to the grid https://cdn.tutsplus.com/webdesign/uploads/legacy/092_960_GridSystem/psd.jpg

The library that can be used is https://github.com/STRML/react-resizable

**Comment by BorisTheB1ad3** [comment]
https://github.com/BorisTheB1ad3/listy/commit/da714af97a9e74e99062d83343476aa6be2510ca
